version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db_portfolio
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd!
      MYSQL_DATABASE: sample_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuser
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/my.cnf.d/my.cnf
    ports:
      - 127.0.0.1:3306:3306
  front:
    build: .
    container_name: portfolio
    volumes:
      - ./app/portfolio:/app
    ports:
      - 127.0.0.1:8080:3000
      - 127.0.0.1:4000:4000
    command: yarn dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
     - db
    tty: true
    stdin_open: true
    privileged: true